server:
  servlet:
    context-path: /batchproject

spring:
  application:
    name: batchproject
  batch:
    jdbc:
      initialize-schema: "always"
#    job:
#      enabled: false
  profiles:
    active: local

